apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: students-api
  description: Retrieve artist details
spec:
  type: openapi
  lifecycle: development
  owner: vikash
  system: students-mgmt-portal
  definition: |
    openapi: "3.0.0"
    info:
      version: 1.0.0
      title: Student API
      license:
        name: MIT
    servers:
      - url: http://localhost:8080/dsi
    paths:
      /check-studentinformation/{id}:
        get:
          summary: List students by id
    ...
