apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: student-app
  description: Student application
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: pep8speaks-org/pep8speaks
  tags:
    - java
    - maven
  links:
    - url: https://admin.example-org.com
      title: Admin Dashboard
      icon: dashboard
      type: admin-dashboard
spec:
  type: api
  lifecycle: development
  owner: vikash1
  system: students-api
  definition: |
    openapi: "3.0.0"
    info:
      version: 1.0.0
      title: Artist API
      license:
        name: MIT
    servers:
      - url: http://localhost:8080/dsi
    paths:
      /check-studentinformation:
        get:
          summary: all student
