package com.xyz.bit.query;

public interface IQuery {

  public static final String UPDATE_RESOURCE_DETAILS =
      new StringBuffer(
          " UPDATE  XYZ_DSI.XYZ_STUDENT SET STUDENT_NAME =?, STUDENT_ADDRESS = ?, STUDENT_GENDER = ?, ")
          .append(
              " STUDENT_EMAIL= ?, STUDENT_QUALIFICATION= ? , STUDENT_MOBILE = ? WHERE STUDENT_REFERENCE_NUMBER = ?")
          .toString();

  public static final String ADD_RESOURCE_PASSWORD =
      new StringBuffer(
          "INSERT INTO XYZ_DSI.XYZ_CREDENTIAL (STUDENT_ID, STUDENT_REFERENCE_NUMBER , STUDENT_PASSWORD) ")
          .append(
              " VALUES ((SELECT STUDENT_ID FROM XYZ_DSI.XYZ_STUDENT WHERE  STUDENT_REFERENCE_NUMBER = ?), ? , ?)")
          .toString();

  public static final String CHECK_RESOURCE_IN_STUDENT =
      "SELECT COUNT(*) FROM XYZ_DSI.XYZ_STUDENT WHERE STUDENT_REFERENCE_NUMBER = ?";

  public static final String CHECK_RESOURCE_IN_CREDENTIAL =
      "SELECT COUNT(*) FROM XYZ_DSI.XYZ_CREDENTIAL WHERE STUDENT_REFERENCE_NUMBER = ?";

  public static final String CHECK_STUDENT_NAME_IN_STUDENT =
      "SELECT STUDENT_NAME FROM XYZ_DSI.XYZ_STUDENT WHERE STUDENT_REFERENCE_NUMBER = ?";

  public static final String CHECK_STUDENT_PASSWORD_IN_CREDENTIAL =
      "SELECT STUDENT_PASSWORD FROM XYZ_DSI.XYZ_CREDENTIAL WHERE STUDENT_REFERENCE_NUMBER = ?";

  public static final String VALIDATE_RESOURCE_IN_CREDENTIAL =
      "SELECT COUNT(*) FROM XYZ_DSI.XYZ_CREDENTIAL WHERE STUDENT_REFERENCE_NUMBER = ? AND STUDENT_PASSWORD = ?";

  public static final String FETCH_STUDENT_TEST =
      new StringBuffer(
          "SELECT TEST.*, STUDENT.STUDENT_ID FROM XYZ_DSI.XYZ_TEST AS TEST, XYZ_DSI.XYZ_STUDENT AS STUDENT, ")
          .append(
              " XYZ_DSI.XYZ_COURSE AS COURSE WHERE STUDENT.COURSE_ID = COURSE.COURSE_ID  AND TEST.COURSE_ID = COURSE.COURSE_ID ")
          .append(" AND STUDENT.STUDENT_REFERENCE_NUMBER = ?").toString();

  public static final String FETCH_RESULT_DATA =
      new StringBuffer(
          "SELECT RESULT.* FROM XYZ_DSI.XYZ_RESULT RESULT, XYZ_DSI.XYZ_STUDENT AS STUDENT ")
          .append(
              " WHERE RESULT.STUDENT_ID = STUDENT.STUDENT_ID AND STUDENT.STUDENT_REFERENCE_NUMBER = ? ")
          .toString();

  public static final String FETCH_STUDENT_TEST_QUESTION =
      "SELECT * FROM XYZ_DSI.XYZ_QUESTION WHERE TEST_ID = "
          + "(SELECT TEST_ID FROM XYZ_DSI.XYZ_TEST WHERE TEST_REFERENCE_NUMBER = ?) ORDER BY QUESTION_ID;";

  public static final String FETCH_STUDENT_TEST_ANSWER =
      "SELECT QUESTION_ID, CORRECT_OPTION FROM XYZ_DSI.XYZ_QUESTION WHERE TEST_ID = "
          + "(SELECT TEST_ID FROM XYZ_DSI.XYZ_TEST WHERE TEST_REFERENCE_NUMBER = ?) ORDER BY QUESTION_ID;";


  public static final String SAVE_RESULT =
      new StringBuffer(
          " INSERT INTO XYZ_DSI.XYZ_RESULT (STUDENT_ID, TEST_ID , REGISTERED, TEST_TAKEN, TEST_TAKEN_DATE, SCORE, TOTAL_QUESTION, CORRECT_ANSWER, INCORRECT_ANSWER) ")
          .append(
              " VALUES ((SELECT STUDENT_ID FROM XYZ_DSI.XYZ_STUDENT WHERE  STUDENT_REFERENCE_NUMBER = ?),")
          .append(
              " (SELECT TEST_ID FROM XYZ_DSI.XYZ_TEST WHERE  TEST_REFERENCE_NUMBER = ?) , ? , ? , ? ,  ? , ? , ? , ?)")
          .toString();

  public static final String GET_RESULT =
      new StringBuffer(
          " SELECT RES.TOTAL_QUESTION, RES.CORRECT_ANSWER, RES.INCORRECT_ANSWER, RES.REGISTERED, ")
          .append(
              " RES.RESULT_ID, RES.STUDENT_ID, RES.TEST_ID, RES.TEST_TAKEN, RES.TEST_TAKEN_DATE,  ")
          .append(
              " ? AS STUDENT_REFERENCE_NUMBER, ? AS TEST_REFERENCE_NUMBER FROM XYZ_DSI.XYZ_RESULT AS RES ")
          .append(
              " WHERE STUDENT_ID  = (SELECT STUDENT_ID FROM XYZ_DSI.XYZ_STUDENT WHERE STUDENT_REFERENCE_NUMBER = ?) ")
          .append(
              " AND TEST_ID  = (SELECT TEST_ID FROM XYZ_DSI.XYZ_TEST WHERE TEST_REFERENCE_NUMBER = ?) ")
          .toString();

  public static final String GET_NOTIFICATION =
      new StringBuffer(" SELECT MESSAGE, START_DATE, END_DATE, PRIORITY ")
          .append(" FROM XYZ_DSI.XYZ_NOTIFICATION").toString();
}
